### PR TITLE
Pin version and convert TTL to int

### PR DESCRIPTION
**Pull request by antoniozh**
I've converted the TTL type to fix the error thrown by Cloudflare API changes:
https://github.com/tiredofit/docker-nginx-proxy-cloudflare-companion/issues/7
Also I've changed the Dockerfile so that the version of the Cloudflare package gets pinned because of the pending library rewrite.

### CODE REVIEW

**Review by tiredofit — APPROVED** [review]

**Comment by tiredofit** [comment]
Thanks! I will merge the PR and make some other minor changes to modernize the image and be back with a release version here shortly.

**Comment by tiredofit** [comment]
Would you by chance be able to test `tiredofit/nginx-proxy-cloudflare-companion:develop` that it executes and updates records as need be?

It is an upgrade to Alpine 3.20 which changes some underlying Python modules, wanting to make sure that they are not broken. I do not have nginx-proxy to test anymore (which is reason as to no updates for the past couple of years).

**Comment by antoniozh** [comment]
I didn't find a develop tag, but I used the 5 hour old latest tag and it works fine for me!

**Comment by tiredofit** [comment]
Interesting. I just repushed it again.

**Pull request merged**
